version: "3.7"

services:
  go:
    build:
      context: api/
    restart: always
    depends_on:
      - db
    volumes:
      - ./api/config.yaml:/config.yaml
    ports:
      - 1323:80

  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: classicmodels
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db-data:/data/postgres
      - ./api/migrations/mysqlsampledatabase.sql:/docker-entrypoint-initdb.d/1_init_schema.sql
    ports:
      - 5432:5432

volumes:
  db-data: